# version of docker
version: "3.8"

# services
#mySQL services
services:
  mysqldb:
    container_name: app-db
    image: mysql:5.7.24
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
    ports:
      - $DB_PORT:$DB_PORT
    command: --character-set-server=utf8
    volumes:
      - db-data:/var/lib/mysql

  #customer services
  app:
    build: .
    image: abinbev
    ports:
      - $PORT:$PORT
    depends_on:
      - mysqldb
    volumes:
      - .:/home/app
    stdin_open: true
    tty: true
volumes:
  db-data:
